version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - saved_exports:/app/exports
      - sessions:/app/sessions
      - keys:/app/keys
    restart: always

volumes:
  saved_exports:
  sessions:
  keys: